### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue.org#1]
We are approaching a point where everything is fairly final.

There are a few more things we would like to do:
 - [x] Add an `Edit this page` type of button for every docs page
 - [x] Review and restructure the `Introduction` category to have a better user flow
 - [ ] Improve readability of code blocks (ligther text on the dark bg?)
 - [x] Make headings clickable / linkable
 - [ ] Add `prev` / `next` links to docs / posts
 - [ ] Add a file for defining author details (username as key -> website, full name etc.)
 - [x] Create a preview component to show the screenshots generated in https://github.com/rigor789/nativescript-vue-ui-tests/tree/master/screenshots
 - [x] Update the landing page with proper content + more graphics
 - [x] Add meta information to every page for better SEO
 - [x] Add google analytics code
 - [x] Add algolia docsearch (once the page is live, and they can index the pages)
 - [ ] Generate an rss / atom feed from the blog
 - [x] Generate a sitemap
 - [x] Create a favicon
 - [x] Make graphics for the different layouts 
 - [x] Explain the layouts in more detail

**Comment by jlooper** [comment]
here are some favicons [Archive.zip](https://github.com/rigor789/nativescript-vue.org/files/1639968/Archive.zip)

**Comment by rigor789** [comment]
Added the favicons, generated different sizes for chrome / safari etc
