### ISSUE TITLE
favicon 404

### ISSUE THREAD

**Issue by tjvantoll** [nativescript-vue/nativescript-vue.org#15]
This is the most trivial of issues, but the favicon link is broke on the site https://nativescript-vue.org/favicon-32x32.png.

**Comment by damain** [comment]
Not as simple as it seems. When I build the docs it copies the images from the static folder to the dist  folder however the files seem corrupted.

**Comment by damain** [comment]
I tried copying the files manually from the static folder to the dist folder and the icons are available in the browser.

**Comment by damain** [comment]
Solved it by replacing the assets plugin with the static plugin. I will do a pull request soon

**Comment by rigor789** [comment]
Thanks ﻿@damain for the fix! :)

**Comment by damain** [comment]
I go as dajo in slack btw

**Comment by rigor789** [comment]
Ah cool! Thanks for letting me know :)

**Comment by tjvantoll** [comment]
Thanks so much @damain!
