### ISSUE TITLE
Mobile image on home page

### ISSUE THREAD

**Issue by kossa** [nativescript-vue/nativescript-vue.org#18]
Hello,

Seems like the top of mobile is larger than the bottom

![image](https://user-images.githubusercontent.com/1175584/36340249-81961588-13d9-11e8-8c22-2e48774c2b8c.png)

**Comment by rigor789** [comment]
It's based on an isometric grid, and the corner radiuses are different to make them visually correct, as a side effect the width might be a tiny bit different, but I don't consider this to be an issue

**Comment by alexziskind1** [comment]
Also, the thickness of this particular phone model is different on the left lower corner. Just for completion :)

<img width="629" alt="screen shot 2018-02-23 at 12 01 55 pm" src="https://user-images.githubusercontent.com/1638579/36606453-c3477dac-1891-11e8-9299-5952cc2cc907.png">

**Comment by rigor789** [comment]
That's a feature of the phone to make it easier to hold in the hand. Scientists have studied the ergonomics of the human hand to determine the right ratio of thickness for the perfect and most comfortable grip.

**Comment by alexziskind1** [comment]
Yes, so two sets of phones are required; iPhone 8-L and iPhone 8-R, for example. To be ergonomically correct for lefties and righties.
