### ISSUE TITLE
Documentation for Frame component has no sidebar entry.

### ISSUE THREAD

**Issue by michael-erwin** [nativescript-vue/nativescript-vue.org#252]
Googling about specific Frame related problem I'm having brought me to this page result:

https://nativescript-vue.org/en/docs/elements/components/frame/

The the documentation helped me find a solution but I noticed it has no entry for sidebar topics under ELEMENTS:COMPONENTS. I think it should have an entry to avoid unnecessary confusion with its usage under the vue context vs. the one found on nativescript core documentation.

**Comment by rigor789** [comment]
This has been fixed in https://github.com/nativescript-vue/nativescript-vue.org/commit/b6f3d2d8d462b737ffca00b319241f184f80ea59
