### ISSUE TITLE
ListPicker Color Divider

### ISSUE THREAD

**Issue by GussRw** [nativescript-vue/nativescript-vue.org#253]
I can not change the color of the dividing line.
I try with ***selectionDivider*** as follows but not working:
```XML
<ListPicker :items="items" v-model="selectedItem" selectionDivider="#fff"/>
```

**Comment by rigor789** [comment]
I don't think the ListPicker has an option to change the separator color (API reference: https://docs.nativescript.org/api-reference/classes/_ui_list_picker_.listpicker)

**Comment by GussRw** [comment]
Thanks for your answer, I did not find a way to change the color of the separator, I finally created my own list with buttons and a scroll view
I think it's not the best idea but it worked.

And I think I'm in the wrong nativescript repository.

**Comment by rigor789** [comment]
I usually end up with using a ListView and implementing a picking feature on top of it - so it should be fine!

As for the repository, we usually track these issues in the main repository here: https://github.com/nativescript-vue/nativescript-vue
