### ISSUE TITLE
License for Documentation

### ISSUE THREAD

**Issue by halfnelson** [nativescript-vue/nativescript-vue.org#259]
This repository doesn't have a LICENSE file. I'd like to use some of these awesome documents as the base for another framework's port to NativeScript. Is it possible to do this?

**Comment by rigor789** [comment]
Added now!

https://github.com/nativescript-vue/nativescript-vue.org/blob/ba9c6198e0271bc58bf22cf881fc81be58bd56ec/LICENSE#L1-L21

**Comment by halfnelson** [comment]
That is great. Thank you
