### ISSUE TITLE
vue-devtools installation

### ISSUE THREAD

**Issue by aranmohyeddin** [nativescript-vue/nativescript-vue.org#282]
from [vue-devtools github](https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md) I read:
>    Make sure you import devtools before Vue, otherwise it might not work as expected.

But [here](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/) the opposite was done:

**Comment by highflyer910** [comment]
May I work on this one?

**Comment by rigor789** [comment]
@highflyer910 sure!

**Comment by rigor789** [comment]
Fixed in #302
