### ISSUE TITLE
Document usage of the Router

### ISSUE THREAD

**Issue by EddyVerbruggen** [nativescript-vue/nativescript-vue.org#40]
I'd be happy to take a stab at documenting usage of `vue-router`, but I'm not entirely sure where in the menu this should live. Suggestions?

**Comment by rigor789** [comment]
There is currently a placeholder for it at https://nativescript-vue.org/en/docs/getting-started/vue-plugins/

But since routing in general is a common topic, I think we should create a new sidebar category dedicated to it. 

Within this category it would be nice to document "routing" without vue-router using `this.$navigateTo` `this.$navigateBack` and `this.$showModal`. And possibly provide examples.

Then we could move on to VueRouter routing, and describe when it should be used. For simple master/detail type of apps I wouldn't recommend VueRouter. 

I'm open for suggestions

**Comment by EddyVerbruggen** [comment]
Sounds good. Perhaps we should rename the current "Using Vue Plugins" page to "Vuex" and add a "Router" sibling page.

Question about `this.$navigateTo`: can I use that from within a template, like one can with `$router`? So something similar to `<Button text="login" @tap="$router.push('/login')" />`?

**Comment by rigor789** [comment]
We could rename those pages, but not sure if `$navigateTo` should be part of the Router page...


As for the second question, yes you can use it like `<Button text="tap me" @tap="$navigateTo()" />` but you need to pass it a component, which you can do within the template as long as it's available (defined in `data` for example).

**Comment by EddyVerbruggen** [comment]
Hmm, that's what I tried actually before asking but it didn't seem to work. I must be doing it wrong.. do you know how to reference the `bar` component here (I removed the irrelevant stuff from the templates)?

```javascript
const Bar = {
    template: `` // my template
}

const Home = {
  template: `<Button text="Go to Bar" @tap="$navigateTo(bar)" />` // this 'bar' param is the issue..
}

new Vue({
    router,
    data: {
        bar: Bar
    },
}
```

**Comment by rigor789** [comment]
```
const Bar = {
    template: `` // my template
}

const Home = {
  data() {
    return { 
      bar: Bar
    }
  },
  template: `<Button text="Go to Bar" @tap="$navigateTo(bar)" />` // this 'bar' param is the issue..
}

new Vue({
  render: h => h(Home)
}
```

The bar has to be defined in the components own scope / data. There are tricks to make it global if you attach it to the Vue prototype or something

**Comment by EddyVerbruggen** [comment]
Awesome! Makes a lot of sense. Thanks for the explanation.

**Comment by EddyVerbruggen** [comment]
How about this terminology?

<img width="238" alt="screen shot 2018-02-21 at 17 48 59" src="https://user-images.githubusercontent.com/1426370/36493290-8845ff0c-172f-11e8-812d-d1bb681b0c41.png">

**Comment by rigor789** [comment]
I think Manual Routing would fit better?

**Comment by zupago** [comment]
I want to know the danger in using Vue Route I started my app with below formate and it works great but I want to know if is bad idea 
 
```
<template>
    <page>
    <router-view></router-view>
    <router-view  name="a"></router-view>
    <router-view  name="b"></router-view> 
  </page>
</template>
<script>

export default {
  name: 'Welcome',

  mounted() {
          if (this.$authcheck) {
            this.$router.push({ name: 'home'})
          }else{
            this.$router.push({ name: 'start'})
          }
        },
  methods: {
    
    }
}
</script>
```

**Comment by diadal** [comment]
I want to know the danger in using Vue Route I started my app with below formate and it works great but I want to know if it's bad idea 
 
```
<template>
    <page>
    <router-view></router-view>
    <router-view  name="a"></router-view>
    <router-view  name="b"></router-view> 
  </page>
</template>
<script>

export default {
  name: 'Welcome',

  mounted() {
          if (this.$authcheck) {
            this.$router.push({ name: 'home'})
          }else{
            this.$router.push({ name: 'start'})
          }
        },
  methods: {
    
    }
}
</script>
```

**Comment by rigor789** [comment]
@diadal well, component based routing is working, but page/frame routing that manual routing covers does not with Vue Router. Difference is that with component routing you don't have a backstack, so all views are created/destroyed when changing a route, which will be a performance bottleneck as you progress

**Comment by diadal** [comment]
@rigor789 you are right already change the method thanks
