### ISSUE TITLE
[Question] Translation Guide

### ISSUE THREAD

**Issue by qgp9** [nativescript-vue/nativescript-vue.org#46]
I would like to translate docs to Korean.
Do we have any guideline for a translation?
Naturally, I presume that I can just fork a repo and add/edit `build/index.js` and `content/docs/ko`.
However, I  would be glad if I can have any other guideline or advice. :-)

**Comment by rigor789** [comment]
Hi, you can open up a PR with the translation (we'd like to keep it in this repo for simplicity)

First thing, edit https://github.com/nativescript-vue/nativescript-vue.org/blob/master/build/index.js#L39-L41
to set the label to be shown in the language selector,

and then add `ko` to the locales array here: https://github.com/nativescript-vue/nativescript-vue.org/blob/master/build/index.js#L113

If you run a build (npm run build) a new folder with the english docs should be created for `ko`. You can then edit these documents and translate them into Korean.

If something is not translated, keep it english and translate it later. Let me know if some of these steps don't work / you need help with things.

I would suggest you open a PR as soon as you start, and that way we can stay in the loop and leave feedback when needed.

**Comment by qgp9** [comment]
Thanks @rigor789 
I'll make a PR soon with a first page and initial environment :-)

**Comment by lex111** [comment]
Hi @rigor789 

I want to make the translation into Russian, but in my own repository, by analogy, as it is currently done with the Russian translation of the Vue.js documentation https://github.com/translation-gang/ru.vuejs.org/

Is this possible?

**Comment by rigor789** [comment]
Hi @lex111 we have chosen a different approach for translations, and we'd like to keep them in the same repository (this one). You can work on the Russian translation in your own repository, but we would have to merge it into this repository. Are there any specific reasons you want to have a separate repository?

**Comment by lex111** [comment]
The fact is that there is such an organization https://github.com/translation-gang in which it is planned to create a new repository for translation documentation this project, it's easier for us to translate in that way and support the translation in the future. We will synchronize through PR, as usual.

**Comment by rigor789** [comment]
Ah very cool org! So the way things are set up currently, you will have to fork the repo, and then PR the changes, but we could try working on a better solution, maybe make the ru directory a submodule or something, and then you can add a webhook when the translation changes for us to re-build the site. Let me know if you want to give that a shot

**Comment by lex111** [comment]
Oh, a good idea, this is to automate, we need to think about that, we plan to start soon, we'll create after PR.
