### ISSUE TITLE
Document `v-view` directive

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue.org#5]
Moving here from https://github.com/nativescript-vue/nativescript-vue/issues/80

**Comment by lukaszb** [comment]
why this has been closed? I do have a hard time trying to figure out how parent view can be implemented using v-view. Docs only mentioned this from the child views perspective.

**Comment by rigor789** [comment]
It has been closed because the docs have been written. Can you elaborate what you mean, and what use case the other way around would cover?
