### ISSUE TITLE
Update TabView docs

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue.org#69]
_From @yassipad on March 26, 2018 8:37_

The event emitted by TabView is `@tabChange` and not `@selectedIndexChanged` unlike what's described in the docs: https://nativescript-vue.org/en/docs/elements/components/tab-view/#events.

_Copied from original issue: nativescript-vue/nativescript-vue#159_

**Comment by ikoevska** [comment]
This seems to be resolved. Currently, docs refer to `tabChange`.
