### ISSUE TITLE
Bug related to the life cycle of an Android application

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue.org#95]
I am on android, once I press the button "back" and that the application is found in pause "onPause ()", and then I click on the icon of the application to engage "surResume ()" then the application bug. Once stop "onStop ()", click on the icon while it normally starts. Bug related to the life cycle of an Android application.

**Comment by rigor789** [comment]
This issue was moved to nativescript-vue/nativescript-vue#185
